platform :ios, '9.0'

target 'SampleApp' do

pod 'TPKeyboardAvoiding'
pod 'SDWebImage'
pod 'MBProgressHUD'
pod 'AFNetworking'

pod 'LGSideMenuController'
pod 'Reachability'
pod 'TPKeyboardAvoiding'

end
